# Change these first
owner: mtr-static-official # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Monika主站
    url: https://monika.love
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : Monika 网盘
    url: https://cloud.monika.love
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : Monika 下载服务
    url: https://dl.monika.love
    expectedStatusCodes:
@@ -36,34 +28,14 @@ sites:
      - 404
  - name : Monika 论坛
    url: https://forum.monika.love
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : Monika 机房
    url: http://cn-zz1.rvh2.rainyun.com/
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : Monika 网盘（应急访问状态）
    url: http://124.132.136.18/
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : DDLC Wiki
    url: https://wiki.monika.love/
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : Monika 主站-重定向
    url: https://next.monika.love/
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : Doki Doki Mod Manager China Mods Site
    url: https://mods.monika.love/
    expectedStatusCodes:
@@ -72,22 +44,10 @@ sites:
      - 404
  - name : Monika 捐助计划
    url: https://donate.monika.love/
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : Monika Mod Manager China Mods API
    url: https://api.monika.love/mod_store.json
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : Natuski 主站
    url: https://natsuki.love
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : 【数据库错误】Yuri 主站
    url: https://yuri.fit/
    expectedStatusCodes:
@@ -104,34 +64,14 @@ sites:
      - 403
  - name : Monika 测试论坛
    url: https://test.monika.love/
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : Sayori主站
    url: https://sayori.love/
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : DDLCTech 论坛
    url: https://forum.ddlc.tech/
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : DDLC 镜像（Coding）
    url: https://mirrors.ddlc.tech/
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : DDLC镜像（Vercel）
    url: https://mirrors.ddlc.wiki/
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : 【MTR】MTR.PUB OutLook 365
    url: http://autodiscover.mtr.pub
    expectedStatusCodes:
@@ -140,28 +80,13 @@ sites:
      - 404
  - name : DDLC PrivateBin服务
    url: https://s.ddlc.top
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : DDLC 社区图床
    url: https://img.ddlc.top
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : DDLC 中文站（主节点）
    url: https://ddlc.top
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name : DDLC 中文站（备用）
    url: https://cn.ddlc.top
    expectedStatusCodes:
      - 200
      - 201
      - 404




status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.ddlc.wiki
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DDLC站点状态
  introTitle: "DDLC站点状态。"
  introMessage: 由Upptime与MTR提供支持。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
