# Change these first
owner: mtr-static-official # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Monika主站
    url: https://monika.love
  - name : Monika 网盘
    url: https://cloud.monika.love
  - name : Monika 下载服务
    url: https://dl.monika.love
  - name : Monika CDN
    url: https://cdn.monika.love
  - name : Monika 第三方MAS更新源
    url: https://update.mas.monika.love/
  - name : Monika 论坛
    url: https://forum.monika.love
  - name : Monika 机房
    url: http://cn-zz1.rvh2.rainyun.com/
  - name : Monika 网盘（应急访问状态）
    url: http://124.132.136.18/
  - name : DDLC Wiki
    url: https://wiki.monika.love/
  - name : Monika 主站-重定向
    url: https://next.monika.love/
  - name : Doki Doki Mod Manager China Mods Site
    url: https://mods.monika.love/
  - name : Monika 捐助计划
    url: https://donate.monika.love/
  - name : Monika Mod Manager China Mods API
    url: https://api.monika.love/mod_store.json
  - name : Natuski 主站
    url: https://natsuki.love
  - name : 【数据库错误】Yuri 主站
    url: https://yuri.fit/
  - name : Monika OneDrive反代服务
    url: https://onedrive.monika.love/
  - name : Monika 测试论坛
    url: https://test.monika.love/
  - name : Sayori主站
    url: https://sayori.love/
  - name : DDLCTech 论坛
    url: https://forum.ddlc.tech/
  - name : DDLC 镜像（Coding）
    url: https://mirrors.ddlc.tech/
  - name : DDLC镜像（Vercel）
    url: https://mirrors.ddlc.wiki/
  - name : 【MTR】MTR.PUB OutLook 365
    url: http://autodiscover.mtr.pub


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.ddlc.wiki
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DDLC站点状态
  introTitle: "DDLC站点状态。"
  introMessage: 由Upptime与MTR提供支持。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
